import type { Items, Quality } from '@/types/items';

export const quality: Quality = {
  common: '#ffffff',
  uncommon: '#00ff15',
  rare: '#0033ff',
  epic: '#8e00ff',
  legendary: '#ff8300',
};

export const qualityRarity = {
  common: 100,
  uncommon: 25,
  rare: 10,
  epic: 5,
  legendary: 0,
};

export const itemTypeSortPriority = {
  weapon: 1,
  helmet: 2,
  body: 3,
  pants: 4,
  ring: 5,
  jewerly: 6,
  potion: 7,
};

const deepFreeze = (obj: Items[]) => {
  Object.getOwnPropertyNames(obj).forEach((prop) => {
    if (typeof obj[prop] === 'object' && obj[prop] !== null && !Object.isFrozen(obj[prop])) {
      deepFreeze(obj[prop]);
    }
  });

  return Object.freeze(obj);
};

export const items: Items[] = deepFreeze([
  {
    name: 'Knife',
    description: 'Suitable for slicing bread, I don’t recommend using it as a weapon',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'weapon',
      damage: 3,
      critChance: 15,
      critMod: 1.5,
    },
    image: '/textures/items/weapons/knife.png',
  },
  {
    name: 'Pickaxe',
    description: 'It`s mine now',
    isStackable: false,
    count: 1,
    quality: 'rare',
    feature: 'Can mine some ore',
    type: {
      name: 'weapon',
      damage: 3,
      critChance: 5,
      critMod: 1.5,
    },
    image: '/textures/items/weapons/pickaxe.png',
  },
  {
    name: 'Battle axe',
    description: 'Suitable for slicing bread, I don’t recommend using it as a weapon',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'weapon',
      damage: 3,
      critChance: 15,
      critMod: 1.5,
    },
    image: '/textures/items/weapons/axe.png',
  },
  {
    name: 'Broken sword',
    description:
      'An exquisite sword that served faithfully some aristocrat, once upon a time. But now it`s yours!',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'weapon',
      damage: 4,
      critChance: 10,
      critMod: 1.5,
    },
    image: '/textures/items/weapons/brokenSword.png',
  },
  {
    name: 'Antique sword',
    description: 'Cool Skeleton`s Sword',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'weapon',
      damage: 5,
      critChance: 7,
      critMod: 2,
    },
    image: '/textures/items/weapons/sword1.png',
  },
  {
    name: 'Falshion',
    description: 'The asshole captain escaped from the ship',
    isStackable: false,
    count: 1,
    quality: 'rare',
    type: {
      name: 'weapon',
      damage: 10,
      critChance: 10,
      critMod: 1.5,
    },
    image: '/textures/items/weapons/Falshion1.png',
  },
  {
    name: 'Spider`s torn',
    description: 'Where does a spider have a place for this sword?',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'weapon',
      damage: 2,
      critChance: 25,
      critMod: 10,
    },
    image: '/textures/items/weapons/sword4.png',
  },
  {
    name: 'Rune sword',
    description: 'Curses in an unknown language are engraved on the blade.',
    isStackable: false,
    count: 1,
    quality: 'epic',
    type: {
      name: 'weapon',
      damage: 23,
      critChance: 25,
      critMod: 1.5,
    },
    image: '/textures/items/weapons/sword3.png',
  },
  {
    name: 'Сlaymore',
    description: 'Balanced sword, slightly bent, slightly rusty.',
    isStackable: false,
    count: 1,
    quality: 'rare',
    type: {
      name: 'weapon',
      damage: 8,
      critChance: 7,
      critMod: 2,
    },
    image: '/textures/items/weapons/sword2.png',
  },
  {
    name: 'Small potion',
    description: 'If there is a small potion, then there must be a large one somewhere?',
    isStackable: true,
    count: 1,
    quality: 'common',
    type: {
      name: 'potion',
      healthRestore: 15,
    },
    image: '/textures/items/smallPotionBottle.png',
  },
  {
    name: 'Oblivion potion',
    description: 'Eye four goat',
    isStackable: true,
    count: 1,
    quality: 'rare',
    feature: 'Resets upgraded skills',
    type: {
      name: 'potion',
      healthRestore: -20,
    },
    image: '/textures/items/oblivionPotion.png',
  },
  {
    name: 'Medium potion',
    description: '0.480 milliliters of pure carcinogens',
    isStackable: true,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'potion',
      healthRestore: 30,
    },
    image: '/textures/items/potionBottle.png',
  },
  {
    name: 'Huge potion',
    description: 'Optimal size for 1 person',
    isStackable: true,
    count: 1,
    quality: 'rare',
    type: {
      name: 'potion',
      healthRestore: 60,
    },
    image: '/textures/items/hugePotionBottle.png',
  },
  {
    name: 'Leather helmet',
    description: 'So that your ears don`t freeze',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'helmet',
      armor: 1,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/helmets/helmet1.png',
  },

  {
    name: 'Leather pants',
    description: 'Everyone has a moment in their life when they walked through the wrong door.',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'pants',
      armor: 2,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/pants/pants1.png',
  },

  {
    name: 'Leather jacket',
    description: 'An old jacket taken from a homeless person',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'body',
      armor: 2,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/body/body1.png',
  },
  {
    name: 'Spider helmet',
    description: 'Suppresses spider sense',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'helmet',
      armor: 1,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 5,
      critMod: 0,
    },
    image: '/textures/items/armor/helmets/helmet4.png',
  },

  {
    name: 'Spider pants',
    description: 'You won`t be able to walk on the walls, unfortunately',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'pants',
      armor: 2,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 5,
      critMod: 0,
    },
    image: '/textures/items/armor/pants/pants3.png',
  },

  {
    name: 'Spider jacket',
    description: 'Does it shoot webs?',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'body',
      armor: 2,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 5,
      critMod: 0,
    },
    image: '/textures/items/armor/body/body3.png',
  },
  {
    name: 'Bowler hat',
    description: 'This thing is much better for cooking than for protection.',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'helmet',
      armor: 3,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/helmets/helmet7.png',
  },

  {
    name: 'Torn pants',
    description: 'It`s not even worth 40 gold',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'pants',
      armor: 1,
      intelligent: 0,
      strength: 0,
      agility: 2,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/pants/pants4.png',
  },

  {
    name: 'Metal chest plate',
    description: 'Metal plate on the chest, cheap and simple',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'body',
      armor: 5,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/body/body4.png',
  },

  {
    name: 'Armored helmet',
    description: 'Now with a strip of metal',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'helmet',
      armor: 2,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/helmets/helmet2.png',
  },
  {
    name: 'Armored jacket',
    description: 'an item',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'body',
      armor: 4,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/body/body2.png',
  },
  {
    name: 'Armored pants',
    description: 'Pants for 40 gold',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'pants',
      armor: 3,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/pants/pants2.png',
  },

  {
    name: 'Redstone necklace',
    description: 'Red means strong',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'jewerly',
      armor: 0,
      intelligent: 0,
      strength: 1,
      agility: 0,
      critChance: 5,
      critMod: 0,
    },
    image: '/textures/items/armor/jewelry/jewelry1.png',
  },
  {
    name: 'Bluestone necklace',
    description: 'Blue means... erm..',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'jewerly',
      armor: 0,
      intelligent: 1,
      strength: 0,
      agility: 0,
      critChance: 5,
      critMod: 0,
    },
    image: '/textures/items/armor/jewelry/jewelry2.png',
  },
  {
    name: 'Purplestone necklace',
    description: 'I dont know',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'jewerly',
      armor: 0,
      intelligent: 0,
      strength: 0,
      agility: 1,
      critChance: 5,
      critMod: 0,
    },
    image: '/textures/items/armor/jewelry/jewelry3.png',
  },
  {
    name: 'M249-para',
    description:
      '5.56×45mm NATO light machine gun powered by gears and magic. No, but what did you want?',
    isStackable: false,
    count: 1,
    quality: 'legendary',
    feature: 'It`s just a dev item',
    type: {
      name: 'weapon',
      damage: 1,
      critChance: 90,
      critMod: 10,
    },
    image: '/textures/items/weapons/m249para.png',
  },
  {
    name: 'Purplestone ring',
    description:
      'Looks like it was made as a test item for the ring slot. no, this is some kind of nonsense',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'ring',
      armor: 0,
      intelligent: 0,
      strength: 0,
      agility: 2,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/rings/ring1.png',
  },
  {
    name: 'Bone amulet',
    description: 'This poor guy`s bone now belongs to you.',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'jewerly',
      armor: 0,
      intelligent: 0,
      strength: 1,
      agility: 0,
      critChance: 2,
      critMod: 0,
    },
    image: '/textures/items/armor/jewelry/jewelry5.png',
  },
  {
    name: 'Spider`s heart',
    description: 'It doesn`t look like a heart',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'jewerly',
      armor: 0,
      intelligent: 0,
      strength: 3,
      agility: 0,
      critChance: 5,
      critMod: 0,
    },
    image: '/textures/items/armor/jewelry/jewelry4.png',
  },
  {
    name: 'Rusty tophelm',
    description: 'In the name of God we go to heaven',
    isStackable: false,
    count: 1,
    quality: 'rare',
    type: {
      name: 'helmet',
      armor: 5,
      intelligent: 0,
      strength: 3,
      agility: 0,
      critChance: 0,
      critMod: 1.5,
    },
    image: '/textures/items/armor/helmets/helmet6.png',
  },
  {
    name: 'Worn gorget',
    description: 'Deus in regnium',
    isStackable: false,
    count: 1,
    quality: 'rare',
    type: {
      name: 'body',
      armor: 3,
      intelligent: 0,
      strength: 0,
      agility: 3,
      critChance: 5,
      critMod: 1.5,
    },
    image: '/textures/items/armor/body/body5.png',
  },
  {
    name: 'Spider`s eye',
    description: 'Is he watching you, or not, it really doesn’t matter',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'ring',
      armor: 0,
      intelligent: 0,
      strength: 0,
      agility: 3,
      critChance: 5,
      critMod: 0,
    },
    image: '/textures/items/armor/rings/ring2.png',
  },
  {
    name: 'Poison saber',
    description: 'Not so poisonous',
    isStackable: false,
    count: 1,
    quality: 'rare',
    type: {
      name: 'weapon',
      damage: 4,
      critChance: 25,
      critMod: 10,
    },
    image: '/textures/items/weapons/sword5.png',
  },
]);
