import type { Items, Quality } from '@/types/items';

export const quality: Quality = {
  common: '#ffffff',
  uncommon: '#00ff15',
  rare: '#0033ff',
  epic: '#8e00ff',
  legendary: '#ff8300',
};

export const items: Items[] = [
  {
    name: 'knife',
    description: 'an item',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'weapon',
      damage: 5,
      critChance: 10,
      critMod: 1.5,
    },
    image: '/textures/items/knife.png',
  },
  {
    name: 'Broken sword',
    description: 'an item',
    isStackable: false,
    count: 1,
    quality: 'uncommon',
    type: {
      name: 'weapon',
      damage: 5,
      critChance: 10,
      critMod: 1.5,
    },
    image: '/textures/items/brokenSword.png',
  },
  {
    name: 'Small potion',
    description: 'an item',
    isStackable: true,
    count: 1,
    quality: 'common',
    type: {
      name: 'potion',
      healthRestore: 15,
    },
    image: '/textures/items/smallPotionBottle.png',
  },
  {
    name: 'Leather helmet',
    description: 'an item',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'helmet',
      armor: 1,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/helmets/helmet1.png',
  },
  {
    name: 'Armored helmet',
    description: 'an item',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'helmet',
      armor: 2,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/helmets/helmet2.png',
  },
  {
    name: 'Leather pants',
    description: 'Everyone has a moment in their life when they walked through the wrong door.',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'pants',
      armor: 2,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/pants/pants1.png',
  },
  {
    name: 'Leather jacket',
    description: 'an old jacket taken from a homeless person',
    isStackable: false,
    count: 1,
    quality: 'common',
    type: {
      name: 'body',
      armor: 2,
      intelligent: 0,
      strength: 0,
      agility: 0,
      critChance: 0,
      critMod: 0,
    },
    image: '/textures/items/armor/body/body1.png',
  },
];
